'use client'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from 'next-themes'


export const metadata = {
  title: 'Harveer Singh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-stone-900">
        <ThemeProvider enableSystem={true} attribute='class'>
        <Navbar />
        {children}
        </ThemeProvider>
        
      </body>
    </html>
  )
}
